name = "grandeprairie-dev"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

# Cloudflare Account
# account_id is read from CLOUDFLARE_ACCOUNT_ID env var or `wrangler login`

[[d1_databases]]
binding = "DB"
database_name = "grandeprairie-dev-db"
database_id = "959887a4-877e-47f7-b046-46fb41fba7c7"

[[kv_namespaces]]
binding = "SESSIONS"
id = "ca2463f3917048d9a1beccac8642d861"

[vars]
ENVIRONMENT = "production"
SITE_URL = "https://grandeprairie.dev"
GITHUB_CLIENT_ID = "Ov23lilk4Mw1MxTACEWk"
GOOGLE_CLIENT_ID = "669514898323-60dfgurqfslmps9bc9samep0qq6o6j2b.apps.googleusercontent.com"
